### ISSUE TITLE
prediction step error: Unable to create dataset (name already exists)

### ISSUE THREAD

**Issue by igwill** [samsledje/D-SCRIPT#12]
Hi Sam,
I've been using your available human ppi trained model to test out some predictions on our data, but I keep getting this error, seen in the tail of the slurm outfile:
```
100%|##########| 14399/14399 [49:31<00:00,  4.85it/s]
  0%|          | 11647/45233277 [3:18:54<12871:51:27,  1.02s/it]
# Using CPU
# Loading Embeddings...
# Making Predictions...
Traceback (most recent call last):
  File "/home/igwill/.local/bin/dscript", line 8, in <module>
    sys.exit(main())
  File "/home/igwill/.local/lib/python3.7/site-packages/dscript/__main__.py", line 54, in main
    args.func(args)
  File "/home/igwill/.local/lib/python3.7/site-packages/dscript/commands/predict.py", line 150, in main
    cmap_file.create_dataset(f"{n0}x{n1}", data=cm.squeeze().cpu().numpy())
  File "/share/apps/anaconda3-97/lib/python3.7/site-packages/h5py/_hl/group.py", line 148, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/share/apps/anaconda3-97/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 137, in make_new_dset
    dset_id = h5d.create(parent.id, name, tid, sid, dcpl=dcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 87, in h5py.h5d.create
ValueError: Unable to create dataset (name already exists)
```

I've tried setting and not setting the --outfile with a name, and running in an otherwise empty dir.

This is how I'm running D-SCRIPT for this step  (just on the CPU for this test prediction run) :
`dscript predict --pairs "/home/igwill/PPI/Dscript/prediction/hypo_cross_ppis_SPTM.tsv" --embeddings "/home/igwill/PPI/Dscript/ppi_allseqs_embed" --model "/home/igwill/PPI/Dscript/prediction/human_v1.sav"`

I see files being made by D-SCRIPT: *.log, .cmaps.h5 (the culprit?), .tsv, .positive.tsv.

Am I mis-setting something here?

Thanks

**Comment by samsledje** [comment]
Hi Will - I will take a more detailed look at this in a little bit -- at a quick look, I would recommend deleting any output files you already have or running with a different -o/--output. *.cmaps.h5 stores the contact map for every pair of predictions, and if you had a run that started and then broke/was cancelled that you tried to re-start, it may be trying to re-write those contact maps with the same name into the same file.

**Comment by samsledje** [comment]
@igwill this should be fixed in the latest commit (1fd94ed7c47f4bde29a7a93d766f890e5d9e13d9). I haven't fully tested, so I'm not going to be uploading a 0.15 version to pip yet -- but you can git clone + `pip install .` or `python setup.py install`. Behavior is now to overwrite a contact map if it already exists in the h5 file, otherwise to create it.

**Comment by igwill** [comment]
Thanks! Just letting you know although it still breaks with that error at the same spot (ppi number 11,647 of ~45M possible ppis to predict) for my actual dataset of interest, it does appear to be working when I fed it my smaller 20%-validation training set (94,770 ppis) as a test. So it if it works for one and not other, guess D-SCRIPT isn't to blame.

**Comment by igwill** [comment]
Hi! Wanted to let you know that I figured out the problem, and it was all me - somehow in this dataset I had duplicated PPIs, and DSCRIPT would crash when trying to re-write that specific protein pair again into the file. The cleaned up PPI .tsv is being predicted on currently, and continues to progress much farther now without error.

**Comment by samsledje** [comment]
@samsledje @rs239 desired behavior if duplicate candidate PPIs -- silently skip? warn user? re-compute and overwrite?

**Comment by rs239** [comment]
good with either, but i'd vote for "recompute and overwrite"-- the robust
way to go and will ensure idempotency. also matches what unix programs
typically do.

ignoring is probably smarter/faster but also has risks (e.g. what if we
made a mistake in saying this should be skipped when it shouldn't have
been)
-r

**Comment by samsledje** [comment]
This was fixed at some point (don't know which commit) by changing L168 of `predict.py` to use `require_dataset`, which gets the data set if it exists and creates if it doesn't. If the data set exists, it overwrites what is there.
