### ISSUE TITLE
Pretrained models?

### ISSUE THREAD

**Issue by fransilvionGenomica** [samsledje/D-SCRIPT#14]
Hi!

Where can I download pretrained models?

**Comment by rs239** [comment]
Here's the link from readthedocs Data page:

Human-data trained model:

http://cb.csail.mit.edu/cb/dscript/data/models/human_v1.sav

**Comment by samsledje** [comment]
All trained models and training/evaluation data can be downloaded here:
https://d-script.readthedocs.io/en/main/data.html

**Comment by fransilvionGenomica** [comment]
Thank you! I saw these links, but I could not open them, it might be a browser problem (I'm using Chrome).
