### ISSUE TITLE
Pre-trained models do not work with "novel" proteins

### ISSUE THREAD

**Issue by Mike1359** [samsledje/D-SCRIPT#15]
Hello,

I am running predict function of d-script with the following inputs taken from the download page:

Code: dscript predict --pairs human_test.tsv --seqs human.fasta --model human_v1.sav

It is working. However, when I try to run it with my own coronavirus sequences that I have added, it gives me an error:

Code: dscript predict --pairs covid_test.tsv --seqs human_extend.fasta --model lm_v1.sav

Error: 

File "/home/msalnik/.local/lib/python3.8/site-packages/dscript/commands/predict.py", line 80, in main
    model = torch.load(modelPath).cpu()
  File "/home/msalnik/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 667, in cpu
    return self._apply(lambda t: t.cpu())
  File "/home/msalnik/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/msalnik/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/msalnik/.local/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 187, in _apply
    self._flat_weights = [(lambda wn: getattr(self, wn) if hasattr(self, wn) else None)(wn) for wn in self._flat_weights_names]
  File "/home/msalnik/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LSTM' object has no attribute '_flat_weights_names'

This is what the coivd_test.tsv looks like inside:
![image](https://user-images.githubusercontent.com/58237458/129043484-7caf81c0-2e19-4c7b-8303-8039771d0ed5.png)

The human_extend.fasta is human.fasta but with these sequences added:
![image](https://user-images.githubusercontent.com/58237458/129043779-30716d53-9438-4453-b1a4-ac1408506cd1.png)

Just a couple of notes:
- I had installed the dscript as a conda environment as detailed in the installation guide
- I have pytorch 1.5, which is the version that was recommended, and looking into the issue I saw that pytorch version was oftentimes responsible for the _flat_weights_names error.

Are there any steps that I am missing for adding novel sequences not in the existing database (human.fasta)?

**Comment by samsledje** [comment]
Hi Mike,

First, make sure you're using `human_v1.sav` as your `--model` argument -- it looks like for the second one above you're using `lm_v1.sav`, which is only the pre-trained language model and is not designed to work with the predict command.

If using the correct model doesn't work, please try updating PyTorch to version 1.7. If this fixes your error, I'll update the conda environment and requirements file. If not, please let me know, and attach your `.tsv` and `.fasta` file (or email to me if you're uncomfortable posting them publicly, samsl@mit.edu) and I'll dig into this further.

**Comment by Mike1359** [comment]
Hi. Sam,

Thank you so much, that seems to have fixed the issue. I can't believe I hadn't noticed such an error on my part. 

If you don't mind, can I ask a question regarding your dataset? I remember reading in your paper on this piece of software about spike proteins being tested. Is it the same dataset and pre-trained model that is available on the website?

**Comment by samsledje** [comment]
Yes, the model used for the SARS prediction is the same `human_v1.sav` that is available for download. The SARS data set comes from [Gorden et al. 2020](https://www.nature.com/articles/s41586-020-2286-9), and the predicted edges can be found [here](http://cb.csail.mit.edu/cb/dscript/data/SARS_CoV_2_Predictions/)
