### ISSUE TITLE
i have no idea how to run the model

### ISSUE THREAD

**Issue by demainchen** [samsledje/D-SCRIPT#17]
When i try to run descript.__main__.py, but Pycharm told me 
"usage: __main__.py [-h] [-v] [-c] {train,eval,embed,predict} ...
__main__.py: error: the following arguments are required: cmd".
I am new in Python, can you please tell me how can i run the model

**Comment by rs239** [comment]
Hi demainchen, we'd suggest using the command line programs that wrap the Python code. Example usage, along with sample files and pre-trained models are provided here: https://d-script.readthedocs.io/en/main/usage.html
