### ISSUE TITLE
How can I use command line to run the model in remote serve?

### ISSUE THREAD

**Issue by demainchen** [samsledje/D-SCRIPT#19]
Now I have entered this model in remote server, the path is "/home/XXXX/XXXX/XXXX/XXXX/D-SCRIPT-main"
When i input " dscript embed --seqs ~//home/XXXX/XXXX/XXXX/XXXX/D-SCRIPT-main/data/seqs/yeast.fasta --outfile yeast.h5" , the terminal told me "Command 'dscript' not found, did you mean:"
I have no idea how to run the code in remote serve. But I succeed in run the code on my computer with the same command line.

**Comment by samsledje** [comment]
Please make sure that dscript is installed on your remote machine -- `pip install dscript`
