### ISSUE TITLE
Cannot reproduce the paper results using default training hyperparameters

### ISSUE THREAD

**Issue by xueeinstein** [samsledje/D-SCRIPT#24]
The pretrained model **human_v1.sav** has good performance as demonstrated in the paper. However, I failed to train it using the default hyperparameters in this repo. 

![image](https://user-images.githubusercontent.com/3424201/131938518-25996632-bd3a-4472-9f5d-662ecec14994.png)
('bb' means using Bepler & Berger's LM as embeddings)

The recall score is especially low and even in decreasing trend. I wonder if the hyperparameters are not suitable or the code is broken in recent commits.

**Comment by samsledje** [comment]
Hi Bill,

Thanks for bringing this to my attention. Can you post what parameters and data set you used in these commands and I can look into it? I will note that we prioritized precision over recall, since we are more concerned with not incorrectly predicting interaction than missing interaction, but that does seem very low.

**Comment by xueeinstein** [comment]
The parameters are the default ones.

We use the following command to extract embeddings of human proteins.

```sh
dscript embed -d cuda --seqs data/seqs/human.fasta --outfile human.h5
```

Then train the model using:

```sh
dscript train --train data/pairs/human_train.tsv \
 --val data/pairs/human_test.tsv \
 --embedding human.h5 --save-prefix bb -d 0
```

**Comment by samsledje** [comment]
Please try using `--use-w`. Eventually we also recommend using `--augment`, but there is currently a bug with data augmentation. I'm working on a bug fix which will make `--use-w` and `--augment` default and will fix the augmentation bug.

**Comment by xueeinstein** [comment]
@samsledje Thanks for your update! We'll try the latest v0.1.6 code and give feedback soon.

**Comment by xueeinstein** [comment]
@samsledje v0.1.6 still cannot reproduce the results so far. We use the default arguments that enable `--use-w` and `--augment`.

```sh
dscript train --train data/pairs/human_train.tsv \
 --val data/pairs/human_test.tsv \
 --embedding human.h5 --save-prefix bb_v016 -d 0
```

<img width="1118" alt="b827e512247bed89fe1597c28ea1a915" src="https://user-images.githubusercontent.com/3424201/133032291-833a477c-5870-491a-8fe1-305c6d122240.png">

**Comment by samsledje** [comment]
Hi Bill, I'm currently looing into this. Thanks for your patience!

**Comment by samsledje** [comment]
Hi Bill,

Please try downloading version 0.1.8 (`pip install dscript==0.1.8`). This should hopefully be resolved, and running `dscript train --train data/pairs/human_train.tsv --test data/pairs/human_test.tsv --embedding [embedding] --output [output] --save-prefix [prefix] --device 0` should now work properly.
