### ISSUE TITLE
Prediction Quality of the human_v1.sav model

### ISSUE THREAD

**Issue by Mike1359** [samsledje/D-SCRIPT#25]
Hello, I was testing the human_v1.sav model on the first 100 positive pairs provided as part of human_test.tsv and human_train.tsv pairs used in the training (200 total). For the predictions, I had noticed that around ~40 of the 100 for each pair set were positive, whereas in the original all of them were positive:

Predicted Positives:

9606.ENSP00000364459	9606.ENSP00000360117	0.9836567640304565
9606.ENSP00000469581	9606.ENSP00000386920	0.9592902660369873
9606.ENSP00000248150	9606.ENSP00000393333	0.8590458035469055
9606.ENSP00000405785	9606.ENSP00000360568	0.9667615294456482
9606.ENSP00000421422	9606.ENSP00000363322	0.7510783076286316
9606.ENSP00000428962	9606.ENSP00000456034	0.9630085825920105
9606.ENSP00000356794	9606.ENSP00000228140	0.9728716015815735
9606.ENSP00000287156	9606.ENSP00000408292	0.7241741418838501
9606.ENSP00000366249	9606.ENSP00000379931	0.9771170020103455
9606.ENSP00000315397	9606.ENSP00000361928	0.9851889610290527
9606.ENSP00000394441	9606.ENSP00000426176	0.9927392601966858
9606.ENSP00000391383	9606.ENSP00000471874	0.9158253073692322
9606.ENSP00000355779	9606.ENSP00000359095	0.8252230882644653
9606.ENSP00000390667	9606.ENSP00000377446	0.9509118795394897
9606.ENSP00000340879	9606.ENSP00000436512	0.8199784755706787
9606.ENSP00000272418	9606.ENSP00000362208	0.8711791038513184
9606.ENSP00000453523	9606.ENSP00000366249	0.9753308296203613
9606.ENSP00000430545	9606.ENSP00000333401	0.9889339208602905
9606.ENSP00000388690	9606.ENSP00000449765	0.8419162034988403
9606.ENSP00000433170	9606.ENSP00000396716	0.9459835886955261
9606.ENSP00000462938	9606.ENSP00000400467	0.9080663323402405
9606.ENSP00000425126	9606.ENSP00000439565	0.863395631313324
9606.ENSP00000463568	9606.ENSP00000361626	0.552105724811554
9606.ENSP00000466020	9606.ENSP00000347168	0.9441595077514648
9606.ENSP00000422772	9606.ENSP00000433170	0.8190745711326599
9606.ENSP00000290541	9606.ENSP00000440327	0.9485920071601868
9606.ENSP00000367806	9606.ENSP00000361076	0.9093227386474609
9606.ENSP00000439565	9606.ENSP00000400082	0.9004131555557251
9606.ENSP00000346148	9606.ENSP00000366488	0.6718304753303528
9606.ENSP00000399076	9606.ENSP00000390331	0.8431304097175598
9606.ENSP00000437062	9606.ENSP00000455856	0.9130898714065552
9606.ENSP00000466634	9606.ENSP00000455282	0.771989107131958
9606.ENSP00000354739	9606.ENSP00000380465	0.9060049057006836
9606.ENSP00000429968	9606.ENSP00000391383	0.7879292368888855
9606.ENSP00000449409	9606.ENSP00000416350	0.610442578792572
9606.ENSP00000266735	9606.ENSP00000423803	0.863314151763916
9606.ENSP00000422772	9606.ENSP00000429374	0.8409360647201538
9606.ENSP00000305682	9606.ENSP00000355694	0.9833050966262817
9606.ENSP00000386752	9606.ENSP00000357823	0.9631509780883789
9606.ENSP00000400666	9606.ENSP00000420277	0.6354408264160156
9606.ENSP00000363018	9606.ENSP00000345156	0.5488811731338501
9606.ENSP00000449391	9606.ENSP00000243067	0.6863182187080383
9606.ENSP00000265339	9606.ENSP00000293968	0.945186972618103
9606.ENSP00000428581	9606.ENSP00000342676	0.9357559680938721
9606.ENSP00000298288	9606.ENSP00000464594	0.9879041314125061
9606.ENSP00000299166	9606.ENSP00000425882	0.9502236843109131
9606.ENSP00000392850	9606.ENSP00000433170	0.9410211443901062
9606.ENSP00000441332	9606.ENSP00000390867	0.9402053356170654
9606.ENSP00000467146	9606.ENSP00000290541	0.8331601619720459
9606.ENSP00000421422	9606.ENSP00000390790	0.9625501036643982
9606.ENSP00000296102	9606.ENSP00000347969	0.8511738777160645
9606.ENSP00000278572	9606.ENSP00000368927	0.9590868353843689
9606.ENSP00000430545	9606.ENSP00000484903	0.9736945033073425
9606.ENSP00000392850	9606.ENSP00000434837	0.8842238783836365
9606.ENSP00000053468	9606.ENSP00000400467	0.946972668170929
9606.ENSP00000470098	9606.ENSP00000466063	0.9452704787254333
9606.ENSP00000452940	9606.ENSP00000418695	0.621618390083313
9606.ENSP00000274242	9606.ENSP00000379888	0.8498455882072449
9606.ENSP00000466142	9606.ENSP00000265339	0.9736203551292419
9606.ENSP00000356720	9606.ENSP00000418933	0.9557900428771973
9606.ENSP00000471874	9606.ENSP00000228140	0.8821477890014648
9606.ENSP00000386920	9606.ENSP00000296102	0.935010552406311
9606.ENSP00000249299	9606.ENSP00000430021	0.6841226816177368
9606.ENSP00000435333	9606.ENSP00000351021	0.8266493678092957
9606.ENSP00000369741	9606.ENSP00000378081	0.8568494915962219
9606.ENSP00000413875	9606.ENSP00000424359	0.9197615385055542
9606.ENSP00000368801	9606.ENSP00000400591	0.9503082036972046
9606.ENSP00000483260	9606.ENSP00000377865	0.8625007271766663
9606.ENSP00000428962	9606.ENSP00000419084	0.9733706116676331
9606.ENSP00000323046	9606.ENSP00000469431	0.9690800905227661
9606.ENSP00000290541	9606.ENSP00000378739	0.9431149959564209
9606.ENSP00000354728	9606.ENSP00000376018	0.9871731996536255
9606.ENSP00000388126	9606.ENSP00000410758	0.8001493215560913
9606.ENSP00000418346	9606.ENSP00000429374	0.9086166620254517
9606.ENSP00000346012	9606.ENSP00000434837	0.9208306670188904
9606.ENSP00000463107	9606.ENSP00000386541	0.8896101117134094
9606.ENSP00000363339	9606.ENSP00000481635	0.6550856828689575
9606.ENSP00000246115	9606.ENSP00000386054	0.8669542670249939
9606.ENSP00000262629	9606.ENSP00000376395	0.6916682720184326
9606.ENSP00000300151	9606.ENSP00000480129	0.9504024982452393

All Predicted:

9606.ENSP00000409077	9606.ENSP00000470819	0.004183880519121885
9606.ENSP00000263904	9606.ENSP00000472680	0.004181481432169676
9606.ENSP00000364459	9606.ENSP00000360117	0.9836567640304565
9606.ENSP00000422403	9606.ENSP00000400591	0.3727874755859375
9606.ENSP00000388332	9606.ENSP00000346080	0.00473413523286581
9606.ENSP00000469581	9606.ENSP00000386920	0.9592902660369873
9606.ENSP00000248150	9606.ENSP00000393333	0.8590458035469055
9606.ENSP00000466266	9606.ENSP00000363315	0.03303053602576256
9606.ENSP00000405785	9606.ENSP00000360568	0.9667615294456482
9606.ENSP00000362930	9606.ENSP00000429312	0.16951589286327362
9606.ENSP00000421422	9606.ENSP00000363322	0.7510783076286316
9606.ENSP00000462683	9606.ENSP00000353015	0.004504330921918154
9606.ENSP00000387127	9606.ENSP00000394483	0.004192233085632324
9606.ENSP00000315476	9606.ENSP00000367498	0.004174979869276285
9606.ENSP00000428962	9606.ENSP00000456034	0.9630085825920105
9606.ENSP00000356794	9606.ENSP00000228140	0.9728716015815735
9606.ENSP00000287156	9606.ENSP00000408292	0.7241741418838501
9606.ENSP00000400467	9606.ENSP00000406561	0.06780070811510086
9606.ENSP00000455282	9606.ENSP00000452473	0.012177504599094391
9606.ENSP00000359862	9606.ENSP00000322594	0.040320705622434616
9606.ENSP00000409852	9606.ENSP00000362994	0.004177952650934458
9606.ENSP00000366249	9606.ENSP00000379931	0.9771170020103455
9606.ENSP00000315397	9606.ENSP00000361928	0.9851889610290527
9606.ENSP00000201031	9606.ENSP00000482258	0.004201050847768784
9606.ENSP00000440658	9606.ENSP00000435311	0.004511235747486353
9606.ENSP00000394441	9606.ENSP00000426176	0.9927392601966858
9606.ENSP00000294179	9606.ENSP00000478403	0.004298059269785881
9606.ENSP00000391383	9606.ENSP00000471874	0.9158253073692322
9606.ENSP00000448229	9606.ENSP00000228140	0.3032079339027405
9606.ENSP00000355779	9606.ENSP00000359095	0.8252230882644653
9606.ENSP00000419084	9606.ENSP00000463395	0.004182545933872461
9606.ENSP00000452636	9606.ENSP00000429323	0.0048737130127847195
9606.ENSP00000390667	9606.ENSP00000377446	0.9509118795394897
9606.ENSP00000340879	9606.ENSP00000436512	0.8199784755706787
9606.ENSP00000413869	9606.ENSP00000484726	0.00418407516553998
9606.ENSP00000272418	9606.ENSP00000362208	0.8711791038513184
9606.ENSP00000453523	9606.ENSP00000366249	0.9753308296203613
9606.ENSP00000485510	9606.ENSP00000358854	0.1316414326429367
9606.ENSP00000436313	9606.ENSP00000406751	0.3218730390071869
9606.ENSP00000417619	9606.ENSP00000360117	0.13994590938091278
9606.ENSP00000360429	9606.ENSP00000347915	0.004184618126600981
9606.ENSP00000476760	9606.ENSP00000473330	0.004178718663752079
9606.ENSP00000430545	9606.ENSP00000333401	0.9889339208602905
9606.ENSP00000388690	9606.ENSP00000449765	0.8419162034988403
9606.ENSP00000452473	9606.ENSP00000356541	0.004236438311636448
9606.ENSP00000433170	9606.ENSP00000396716	0.9459835886955261
9606.ENSP00000402423	9606.ENSP00000426111	0.0041794609278440475
9606.ENSP00000357887	9606.ENSP00000362166	0.004217073321342468
9606.ENSP00000458237	9606.ENSP00000304127	0.00913697574287653
9606.ENSP00000462938	9606.ENSP00000400467	0.9080663323402405
9606.ENSP00000306033	9606.ENSP00000466593	0.004175788722932339
9606.ENSP00000456246	9606.ENSP00000356903	0.007225535809993744
9606.ENSP00000425126	9606.ENSP00000439565	0.863395631313324
9606.ENSP00000400666	9606.ENSP00000463889	0.004179061856120825
9606.ENSP00000273156	9606.ENSP00000372210	0.15635330975055695
9606.ENSP00000464883	9606.ENSP00000405454	0.017727287486195564
9606.ENSP00000376256	9606.ENSP00000362815	0.004175873938947916
9606.ENSP00000431517	9606.ENSP00000468749	0.004177439026534557
9606.ENSP00000391730	9606.ENSP00000453880	0.004175685811787844
9606.ENSP00000463568	9606.ENSP00000361626	0.552105724811554
9606.ENSP00000460400	9606.ENSP00000381963	0.0041790003888309
9606.ENSP00000275603	9606.ENSP00000365944	0.004179549869149923
9606.ENSP00000466020	9606.ENSP00000347168	0.9441595077514648
9606.ENSP00000380196	9606.ENSP00000448030	0.004200428258627653
9606.ENSP00000422772	9606.ENSP00000433170	0.8190745711326599
9606.ENSP00000290541	9606.ENSP00000440327	0.9485920071601868
9606.ENSP00000367806	9606.ENSP00000361076	0.9093227386474609
9606.ENSP00000439565	9606.ENSP00000400082	0.9004131555557251
9606.ENSP00000346148	9606.ENSP00000366488	0.6718304753303528
9606.ENSP00000451345	9606.ENSP00000319578	0.02991567924618721
9606.ENSP00000399076	9606.ENSP00000390331	0.8431304097175598
9606.ENSP00000350625	9606.ENSP00000408482	0.004186746198683977
9606.ENSP00000437062	9606.ENSP00000455856	0.9130898714065552
9606.ENSP00000466634	9606.ENSP00000455282	0.771989107131958
9606.ENSP00000264639	9606.ENSP00000401724	0.00619113864377141
9606.ENSP00000405965	9606.ENSP00000452486	0.004188647493720055
9606.ENSP00000354739	9606.ENSP00000380465	0.9060049057006836
9606.ENSP00000429968	9606.ENSP00000391383	0.7879292368888855
9606.ENSP00000449409	9606.ENSP00000416350	0.610442578792572
9606.ENSP00000467831	9606.ENSP00000400508	0.004181521479040384
9606.ENSP00000455392	9606.ENSP00000376246	0.004175132606178522
9606.ENSP00000266735	9606.ENSP00000423803	0.863314151763916
9606.ENSP00000340677	9606.ENSP00000480077	0.004175209905952215
9606.ENSP00000460084	9606.ENSP00000415430	0.00417515030130744
9606.ENSP00000422772	9606.ENSP00000429374	0.8409360647201538
9606.ENSP00000305682	9606.ENSP00000355694	0.9833050966262817
9606.ENSP00000386752	9606.ENSP00000357823	0.9631509780883789
9606.ENSP00000364320	9606.ENSP00000357857	0.004175729118287563
9606.ENSP00000400666	9606.ENSP00000420277	0.6354408264160156
9606.ENSP00000325421	9606.ENSP00000364204	0.004290678072720766
9606.ENSP00000236273	9606.ENSP00000424616	0.004183924291282892
9606.ENSP00000302176	9606.ENSP00000340817	0.00417567603290081
9606.ENSP00000361076	9606.ENSP00000279259	0.031076163053512573
9606.ENSP00000412530	9606.ENSP00000279259	0.008396787568926811
9606.ENSP00000386792	9606.ENSP00000370208	0.004656988196074963
9606.ENSP00000439818	9606.ENSP00000466103	0.004299112595617771
9606.ENSP00000363018	9606.ENSP00000345156	0.5488811731338501
9606.ENSP00000449391	9606.ENSP00000243067	0.6863182187080383
9606.ENSP00000285018	9606.ENSP00000418389	0.004180514719337225
9606.ENSP00000397912	9606.ENSP00000389381	0.08798135071992874
9606.ENSP00000265339	9606.ENSP00000293968	0.945186972618103
9606.ENSP00000259727	9606.ENSP00000419851	0.076852947473526
9606.ENSP00000480334	9606.ENSP00000395401	0.01999049074947834
9606.ENSP00000225728	9606.ENSP00000255764	0.1401696503162384
9606.ENSP00000345963	9606.ENSP00000478877	0.36111822724342346
9606.ENSP00000468663	9606.ENSP00000326500	0.08016742020845413
9606.ENSP00000428581	9606.ENSP00000342676	0.9357559680938721
9606.ENSP00000362937	9606.ENSP00000401470	0.00417680200189352
9606.ENSP00000296792	9606.ENSP00000451345	0.004193365573883057
9606.ENSP00000261597	9606.ENSP00000476760	0.004182123113423586
9606.ENSP00000298288	9606.ENSP00000464594	0.9879041314125061
9606.ENSP00000299166	9606.ENSP00000425882	0.9502236843109131
9606.ENSP00000392850	9606.ENSP00000433170	0.9410211443901062
9606.ENSP00000441332	9606.ENSP00000390867	0.9402053356170654
9606.ENSP00000252440	9606.ENSP00000337853	0.004177470691502094
9606.ENSP00000415973	9606.ENSP00000361626	0.07606470584869385
9606.ENSP00000446013	9606.ENSP00000380998	0.004191002808511257
9606.ENSP00000467146	9606.ENSP00000290541	0.8331601619720459
9606.ENSP00000452636	9606.ENSP00000431800	0.004373032134026289
9606.ENSP00000421422	9606.ENSP00000390790	0.9625501036643982
9606.ENSP00000386500	9606.ENSP00000429419	0.004411790519952774
9606.ENSP00000296102	9606.ENSP00000347969	0.8511738777160645
9606.ENSP00000400211	9606.ENSP00000324944	0.004174448549747467
9606.ENSP00000337853	9606.ENSP00000485133	0.0870395228266716
9606.ENSP00000278572	9606.ENSP00000368927	0.9590868353843689
9606.ENSP00000430545	9606.ENSP00000484903	0.9736945033073425
9606.ENSP00000392850	9606.ENSP00000434837	0.8842238783836365
9606.ENSP00000053468	9606.ENSP00000400467	0.946972668170929
9606.ENSP00000400727	9606.ENSP00000451252	0.11200016736984253
9606.ENSP00000348838	9606.ENSP00000356479	0.05801907554268837
9606.ENSP00000470098	9606.ENSP00000466063	0.9452704787254333
9606.ENSP00000457239	9606.ENSP00000427514	0.004312561824917793
9606.ENSP00000350098	9606.ENSP00000424048	0.004175967071205378
9606.ENSP00000324124	9606.ENSP00000432154	0.1811545193195343
9606.ENSP00000427365	9606.ENSP00000434816	0.011811366304755211
9606.ENSP00000480549	9606.ENSP00000314458	0.004189439117908478
9606.ENSP00000438284	9606.ENSP00000453560	0.45608770847320557
9606.ENSP00000452940	9606.ENSP00000418695	0.621618390083313
9606.ENSP00000274242	9606.ENSP00000379888	0.8498455882072449
9606.ENSP00000466142	9606.ENSP00000265339	0.9736203551292419
9606.ENSP00000422772	9606.ENSP00000471185	0.06107671186327934
9606.ENSP00000369162	9606.ENSP00000481646	0.2004823088645935
9606.ENSP00000296555	9606.ENSP00000293968	0.006630090065300465
9606.ENSP00000358300	9606.ENSP00000358320	0.004874304868280888
9606.ENSP00000356720	9606.ENSP00000418933	0.9557900428771973
9606.ENSP00000448615	9606.ENSP00000439952	0.004177016206085682
9606.ENSP00000471874	9606.ENSP00000228140	0.8821477890014648
9606.ENSP00000386920	9606.ENSP00000296102	0.935010552406311
9606.ENSP00000482557	9606.ENSP00000480472	0.0042853280901908875
9606.ENSP00000429384	9606.ENSP00000362105	0.004279043525457382
9606.ENSP00000249299	9606.ENSP00000430021	0.6841226816177368
9606.ENSP00000463202	9606.ENSP00000478887	0.004179484210908413
9606.ENSP00000273047	9606.ENSP00000310406	0.004185174126178026
9606.ENSP00000435333	9606.ENSP00000351021	0.8266493678092957
9606.ENSP00000383941	9606.ENSP00000403891	0.0041751619428396225
9606.ENSP00000453972	9606.ENSP00000394014	0.06416654586791992
9606.ENSP00000464599	9606.ENSP00000451345	0.12590646743774414
9606.ENSP00000466791	9606.ENSP00000400467	0.0045409612357616425
9606.ENSP00000437996	9606.ENSP00000382966	0.004204932600259781
9606.ENSP00000358854	9606.ENSP00000432154	0.0042976695112884045
9606.ENSP00000293860	9606.ENSP00000361171	0.00426383875310421
9606.ENSP00000369741	9606.ENSP00000378081	0.8568494915962219
9606.ENSP00000413875	9606.ENSP00000424359	0.9197615385055542
9606.ENSP00000261015	9606.ENSP00000265245	0.008206214755773544
9606.ENSP00000368801	9606.ENSP00000400591	0.9503082036972046
9606.ENSP00000483260	9606.ENSP00000377865	0.8625007271766663
9606.ENSP00000266735	9606.ENSP00000475218	0.05284871533513069
9606.ENSP00000323099	9606.ENSP00000465569	0.00418142369017005
9606.ENSP00000428962	9606.ENSP00000419084	0.9733706116676331
9606.ENSP00000323046	9606.ENSP00000469431	0.9690800905227661
9606.ENSP00000386469	9606.ENSP00000419782	0.004180506803095341
9606.ENSP00000259895	9606.ENSP00000358487	0.004174997564405203
9606.ENSP00000290541	9606.ENSP00000378739	0.9431149959564209
9606.ENSP00000354728	9606.ENSP00000376018	0.9871731996536255
9606.ENSP00000428884	9606.ENSP00000341268	0.00417519174516201
9606.ENSP00000388126	9606.ENSP00000410758	0.8001493215560913
9606.ENSP00000435766	9606.ENSP00000416120	0.07131560891866684
9606.ENSP00000362797	9606.ENSP00000420946	0.019188711419701576
9606.ENSP00000261416	9606.ENSP00000455545	0.004202495329082012
9606.ENSP00000261015	9606.ENSP00000400542	0.2885924279689789
9606.ENSP00000418346	9606.ENSP00000429374	0.9086166620254517
9606.ENSP00000346012	9606.ENSP00000434837	0.9208306670188904
9606.ENSP00000479931	9606.ENSP00000384046	0.004173992667347193
9606.ENSP00000463107	9606.ENSP00000386541	0.8896101117134094
9606.ENSP00000360876	9606.ENSP00000353483	0.004179186653345823
9606.ENSP00000363339	9606.ENSP00000481635	0.6550856828689575
9606.ENSP00000402142	9606.ENSP00000388246	0.004798989277333021
9606.ENSP00000482258	9606.ENSP00000458430	0.004259957931935787
9606.ENSP00000246115	9606.ENSP00000386054	0.8669542670249939
9606.ENSP00000452595	9606.ENSP00000475909	0.00420505041256547
9606.ENSP00000262629	9606.ENSP00000376395	0.6916682720184326
9606.ENSP00000300151	9606.ENSP00000480129	0.9504024982452393
9606.ENSP00000418641	9606.ENSP00000419084	0.06059009209275246
9606.ENSP00000438450	9606.ENSP00000429901	0.008720356971025467
9606.ENSP00000353202	9606.ENSP00000362659	0.00427031796425581
9606.ENSP00000391114	9606.ENSP00000436218	0.008428175002336502
9606.ENSP00000415508	9606.ENSP00000384123	0.03511521965265274
9606.ENSP00000352333	9606.ENSP00000476100	0.004223955329507589
9606.ENSP00000209884	9606.ENSP00000216225	0.004192270804196596

Original:
9606.ENSP00000409077	9606.ENSP00000470819	1
9606.ENSP00000263904	9606.ENSP00000472680	1
9606.ENSP00000364459	9606.ENSP00000360117	1
9606.ENSP00000422403	9606.ENSP00000400591	1
9606.ENSP00000388332	9606.ENSP00000346080	1
9606.ENSP00000469581	9606.ENSP00000386920	1
9606.ENSP00000248150	9606.ENSP00000393333	1
9606.ENSP00000466266	9606.ENSP00000363315	1
9606.ENSP00000405785	9606.ENSP00000360568	1
9606.ENSP00000362930	9606.ENSP00000429312	1
9606.ENSP00000421422	9606.ENSP00000363322	1
9606.ENSP00000462683	9606.ENSP00000353015	1
9606.ENSP00000387127	9606.ENSP00000394483	1
9606.ENSP00000315476	9606.ENSP00000367498	1
9606.ENSP00000428962	9606.ENSP00000456034	1
9606.ENSP00000356794	9606.ENSP00000228140	1
9606.ENSP00000287156	9606.ENSP00000408292	1
9606.ENSP00000400467	9606.ENSP00000406561	1
9606.ENSP00000455282	9606.ENSP00000452473	1
9606.ENSP00000359862	9606.ENSP00000322594	1
9606.ENSP00000409852	9606.ENSP00000362994	1
9606.ENSP00000366249	9606.ENSP00000379931	1
9606.ENSP00000315397	9606.ENSP00000361928	1
9606.ENSP00000201031	9606.ENSP00000482258	1
9606.ENSP00000440658	9606.ENSP00000435311	1
9606.ENSP00000394441	9606.ENSP00000426176	1
9606.ENSP00000294179	9606.ENSP00000478403	1
9606.ENSP00000391383	9606.ENSP00000471874	1
9606.ENSP00000448229	9606.ENSP00000228140	1
9606.ENSP00000355779	9606.ENSP00000359095	1
9606.ENSP00000419084	9606.ENSP00000463395	1
9606.ENSP00000452636	9606.ENSP00000429323	1
9606.ENSP00000390667	9606.ENSP00000377446	1
9606.ENSP00000340879	9606.ENSP00000436512	1
9606.ENSP00000413869	9606.ENSP00000484726	1
9606.ENSP00000272418	9606.ENSP00000362208	1
9606.ENSP00000453523	9606.ENSP00000366249	1
9606.ENSP00000485510	9606.ENSP00000358854	1
9606.ENSP00000436313	9606.ENSP00000406751	1
9606.ENSP00000417619	9606.ENSP00000360117	1
9606.ENSP00000360429	9606.ENSP00000347915	1
9606.ENSP00000476760	9606.ENSP00000473330	1
9606.ENSP00000430545	9606.ENSP00000333401	1
9606.ENSP00000388690	9606.ENSP00000449765	1
9606.ENSP00000452473	9606.ENSP00000356541	1
9606.ENSP00000433170	9606.ENSP00000396716	1
9606.ENSP00000402423	9606.ENSP00000426111	1
9606.ENSP00000357887	9606.ENSP00000362166	1
9606.ENSP00000458237	9606.ENSP00000304127	1
9606.ENSP00000462938	9606.ENSP00000400467	1
9606.ENSP00000306033	9606.ENSP00000466593	1
9606.ENSP00000456246	9606.ENSP00000356903	1
9606.ENSP00000425126	9606.ENSP00000439565	1
9606.ENSP00000400666	9606.ENSP00000463889	1
9606.ENSP00000273156	9606.ENSP00000372210	1
9606.ENSP00000464883	9606.ENSP00000405454	1
9606.ENSP00000376256	9606.ENSP00000362815	1
9606.ENSP00000431517	9606.ENSP00000468749	1
9606.ENSP00000391730	9606.ENSP00000453880	1
9606.ENSP00000463568	9606.ENSP00000361626	1
9606.ENSP00000460400	9606.ENSP00000381963	1
9606.ENSP00000275603	9606.ENSP00000365944	1
9606.ENSP00000466020	9606.ENSP00000347168	1
9606.ENSP00000380196	9606.ENSP00000448030	1
9606.ENSP00000422772	9606.ENSP00000433170	1
9606.ENSP00000290541	9606.ENSP00000440327	1
9606.ENSP00000367806	9606.ENSP00000361076	1
9606.ENSP00000439565	9606.ENSP00000400082	1
9606.ENSP00000346148	9606.ENSP00000366488	1
9606.ENSP00000451345	9606.ENSP00000319578	1
9606.ENSP00000399076	9606.ENSP00000390331	1
9606.ENSP00000350625	9606.ENSP00000408482	1
9606.ENSP00000437062	9606.ENSP00000455856	1
9606.ENSP00000466634	9606.ENSP00000455282	1
9606.ENSP00000264639	9606.ENSP00000401724	1
9606.ENSP00000405965	9606.ENSP00000452486	1
9606.ENSP00000354739	9606.ENSP00000380465	1
9606.ENSP00000429968	9606.ENSP00000391383	1
9606.ENSP00000449409	9606.ENSP00000416350	1
9606.ENSP00000467831	9606.ENSP00000400508	1
9606.ENSP00000455392	9606.ENSP00000376246	1
9606.ENSP00000266735	9606.ENSP00000423803	1
9606.ENSP00000340677	9606.ENSP00000480077	1
9606.ENSP00000460084	9606.ENSP00000415430	1
9606.ENSP00000422772	9606.ENSP00000429374	1
9606.ENSP00000305682	9606.ENSP00000355694	1
9606.ENSP00000386752	9606.ENSP00000357823	1
9606.ENSP00000364320	9606.ENSP00000357857	1
9606.ENSP00000400666	9606.ENSP00000420277	1
9606.ENSP00000325421	9606.ENSP00000364204	1
9606.ENSP00000236273	9606.ENSP00000424616	1
9606.ENSP00000302176	9606.ENSP00000340817	1
9606.ENSP00000361076	9606.ENSP00000279259	1
9606.ENSP00000412530	9606.ENSP00000279259	1
9606.ENSP00000386792	9606.ENSP00000370208	1
9606.ENSP00000439818	9606.ENSP00000466103	1
9606.ENSP00000363018	9606.ENSP00000345156	1
9606.ENSP00000449391	9606.ENSP00000243067	1
9606.ENSP00000285018	9606.ENSP00000418389	1

9606.ENSP00000397912	9606.ENSP00000389381	1
9606.ENSP00000265339	9606.ENSP00000293968	1
9606.ENSP00000259727	9606.ENSP00000419851	1
9606.ENSP00000480334	9606.ENSP00000395401	1
9606.ENSP00000225728	9606.ENSP00000255764	1
9606.ENSP00000345963	9606.ENSP00000478877	1
9606.ENSP00000468663	9606.ENSP00000326500	1
9606.ENSP00000428581	9606.ENSP00000342676	1
9606.ENSP00000362937	9606.ENSP00000401470	1
9606.ENSP00000296792	9606.ENSP00000451345	1
9606.ENSP00000261597	9606.ENSP00000476760	1
9606.ENSP00000298288	9606.ENSP00000464594	1
9606.ENSP00000299166	9606.ENSP00000425882	1
9606.ENSP00000392850	9606.ENSP00000433170	1
9606.ENSP00000441332	9606.ENSP00000390867	1
9606.ENSP00000252440	9606.ENSP00000337853	1
9606.ENSP00000415973	9606.ENSP00000361626	1
9606.ENSP00000446013	9606.ENSP00000380998	1
9606.ENSP00000467146	9606.ENSP00000290541	1
9606.ENSP00000452636	9606.ENSP00000431800	1
9606.ENSP00000421422	9606.ENSP00000390790	1
9606.ENSP00000386500	9606.ENSP00000429419	1
9606.ENSP00000296102	9606.ENSP00000347969	1
9606.ENSP00000400211	9606.ENSP00000324944	1
9606.ENSP00000337853	9606.ENSP00000485133	1
9606.ENSP00000278572	9606.ENSP00000368927	1
9606.ENSP00000430545	9606.ENSP00000484903	1
9606.ENSP00000392850	9606.ENSP00000434837	1
9606.ENSP00000053468	9606.ENSP00000400467	1
9606.ENSP00000400727	9606.ENSP00000451252	1
9606.ENSP00000348838	9606.ENSP00000356479	1
9606.ENSP00000470098	9606.ENSP00000466063	1
9606.ENSP00000457239	9606.ENSP00000427514	1
9606.ENSP00000350098	9606.ENSP00000424048	1
9606.ENSP00000324124	9606.ENSP00000432154	1
9606.ENSP00000427365	9606.ENSP00000434816	1
9606.ENSP00000480549	9606.ENSP00000314458	1
9606.ENSP00000438284	9606.ENSP00000453560	1
9606.ENSP00000452940	9606.ENSP00000418695	1
9606.ENSP00000274242	9606.ENSP00000379888	1
9606.ENSP00000466142	9606.ENSP00000265339	1
9606.ENSP00000422772	9606.ENSP00000471185	1
9606.ENSP00000369162	9606.ENSP00000481646	1
9606.ENSP00000296555	9606.ENSP00000293968	1
9606.ENSP00000358300	9606.ENSP00000358320	1
9606.ENSP00000356720	9606.ENSP00000418933	1
9606.ENSP00000448615	9606.ENSP00000439952	1
9606.ENSP00000471874	9606.ENSP00000228140	1
9606.ENSP00000386920	9606.ENSP00000296102	1
9606.ENSP00000482557	9606.ENSP00000480472	1
9606.ENSP00000429384	9606.ENSP00000362105	1
9606.ENSP00000249299	9606.ENSP00000430021	1
9606.ENSP00000463202	9606.ENSP00000478887	1
9606.ENSP00000273047	9606.ENSP00000310406	1
9606.ENSP00000435333	9606.ENSP00000351021	1
9606.ENSP00000383941	9606.ENSP00000403891	1
9606.ENSP00000453972	9606.ENSP00000394014	1
9606.ENSP00000464599	9606.ENSP00000451345	1
9606.ENSP00000466791	9606.ENSP00000400467	1
9606.ENSP00000437996	9606.ENSP00000382966	1
9606.ENSP00000358854	9606.ENSP00000432154	1
9606.ENSP00000293860	9606.ENSP00000361171	1
9606.ENSP00000369741	9606.ENSP00000378081	1
9606.ENSP00000413875	9606.ENSP00000424359	1
9606.ENSP00000261015	9606.ENSP00000265245	1
9606.ENSP00000368801	9606.ENSP00000400591	1
9606.ENSP00000483260	9606.ENSP00000377865	1
9606.ENSP00000266735	9606.ENSP00000475218	1
9606.ENSP00000323099	9606.ENSP00000465569	1
9606.ENSP00000428962	9606.ENSP00000419084	1
9606.ENSP00000323046	9606.ENSP00000469431	1
9606.ENSP00000386469	9606.ENSP00000419782	1
9606.ENSP00000259895	9606.ENSP00000358487	1
9606.ENSP00000290541	9606.ENSP00000378739	1
9606.ENSP00000354728	9606.ENSP00000376018	1
9606.ENSP00000428884	9606.ENSP00000341268	1
9606.ENSP00000388126	9606.ENSP00000410758	1
9606.ENSP00000435766	9606.ENSP00000416120	1
9606.ENSP00000362797	9606.ENSP00000420946	1
9606.ENSP00000261416	9606.ENSP00000455545	1
9606.ENSP00000261015	9606.ENSP00000400542	1
9606.ENSP00000418346	9606.ENSP00000429374	1
9606.ENSP00000346012	9606.ENSP00000434837	1
9606.ENSP00000479931	9606.ENSP00000384046	1
9606.ENSP00000463107	9606.ENSP00000386541	1
9606.ENSP00000360876	9606.ENSP00000353483	1
9606.ENSP00000363339	9606.ENSP00000481635	1
9606.ENSP00000402142	9606.ENSP00000388246	1
9606.ENSP00000482258	9606.ENSP00000458430	1
9606.ENSP00000246115	9606.ENSP00000386054	1
9606.ENSP00000452595	9606.ENSP00000475909	1
9606.ENSP00000262629	9606.ENSP00000376395	1
9606.ENSP00000300151	9606.ENSP00000480129	1
9606.ENSP00000418641	9606.ENSP00000419084	1
9606.ENSP00000438450	9606.ENSP00000429901	1
9606.ENSP00000353202	9606.ENSP00000362659	1
9606.ENSP00000391114	9606.ENSP00000436218	1
9606.ENSP00000415508	9606.ENSP00000384123	1
9606.ENSP00000352333	9606.ENSP00000476100	1
9606.ENSP00000209884	9606.ENSP00000216225	1

I was just wondering is this a normal result for a prediction, given how the datapoints were used in the training?

**Comment by samsledje** [comment]
Hi Mike -- thanks for pointing this out, this is a good observation. We prioritized precision in our model at the expense of recall, which is to say we are more concerned with accidentally saying something interacts when it doesn't, than we are with missing a true interacting pair. As a result, there will definitely be some true positive edges that are missed by the model.
