### ISSUE TITLE
Data request: pre-computed PPIs

### ISSUE THREAD

**Issue by lcscs12345** [samsledje/D-SCRIPT#26]
Hi Sam,

Hope you are doing well. I find D-SCRIPT very easy to install and use.

Could you explain how to generate the results in Table 1, H. sapiens (5-fold cross validation)? Especially how these relate to human_test.tsv and human_train.tsv in d-script/data/pairs/?

It would be very handy if you could share the predicted PPIs (D-SCRIPT result files) for Table 1, so that we don't have to rerun the tool for the same protein pairs. So far I got D-SCRIPT running very well on a single server but not yet on HPC.

Many thanks,
CS

**Comment by samsledje** [comment]
Hi Chun Shen,

Thank you for the kind comments. The results from Table 1 are based on the pre-trained model, which is available as `Human data trained model` [here](https://d-script.readthedocs.io/en/main/data.html#trained-models), on each of the test data sets [here](https://d-script.readthedocs.io/en/main/data.html#trained-models).

I'm unable to do so right now, but I can shortly make available the predictions on each of the test sets and update you.

**Comment by samsledje** [comment]
Hi Chun Shen,

D-SCRIPT predictions on each of the benchmark data sets are available for download [here](http://cb.csail.mit.edu/cb/dscript/data/Benchmark_Predictions/).

**Comment by lcscs12345** [comment]
Hi @samsledje, I am a bit confused with the [human_train](https://github.com/samsledje/D-SCRIPT/blob/main/data/pairs/human_train.tsv), [human_test](https://github.com/samsledje/D-SCRIPT/blob/main/data/pairs/human_test.tsv) and [Benchmark_Predictions](http://cb.csail.mit.edu/cb/dscript/data/Benchmark_Predictions/) datasets. There are 39818 pairs in common between [human_train](https://github.com/samsledje/D-SCRIPT/blob/main/data/pairs/human_train.tsv) and [Benchmark_Predictions](http://cb.csail.mit.edu/cb/dscript/data/Benchmark_Predictions/), and 4971 pairs in common between [human_test](https://github.com/samsledje/D-SCRIPT/blob/main/data/pairs/human_test.tsv) and [Benchmark_Predictions](http://cb.csail.mit.edu/cb/dscript/data/Benchmark_Predictions/).

Is the [pre-trained model](http://cb.csail.mit.edu/cb/dscript/data/models/human_v1.sav) trained using [human_train](https://github.com/samsledje/D-SCRIPT/blob/main/data/pairs/human_train.tsv)?

**Comment by samsledje** [comment]
Yes, the original dscript and topsy-turvy pre-trained models were both trained using the `human_train` subset.
