### ISSUE TITLE
How to handle pairs that cause GPU memory error

### ISSUE THREAD

**Issue by samsledje** [samsledje/D-SCRIPT#4]
run on cpu? skip silently? skip and report on stdout? skip and report in log file?

**Comment by rs239** [comment]
In order of my preference
 - skip and report in log file
 - try on cpu
 - report in output with a special value (eg -999)
 - skip silently


-------------------------------------------------------------
Rohit Singh | http://people.csail.mit.edu/rsingh

**Comment by samsledje** [comment]
Added logging - v0.1.3 will include skipping too-large pairs and reporting to log file during prediction. holding off on implementing logging across all commands until I have time to test.
