### ISSUE TITLE
Confusions about embedding dimensions

### ISSUE THREAD

**Issue by xingyu617** [samsledje/D-SCRIPT#40]
Hello,

In `train.py`, line 255:  `cm, ph = model.map_predict(z_a, z_b)`,  the dimension of `z_a, z_b` should be Nxd.
In `interaction.py`, line 156, the function `map_predict` states that z0 and z1 should have dimension bxNxd.
At line 168, z0 and z1 is passed to `cpred`, which calls function `cmap ` in `contact.py`.
In` contact.py` all embeddings are treated as 3d tensors (bxNxd). If I understand correctly, the actual embeddings that are fed to `contact.py` have dimension Nxd, which may cause an error, for example, line 43 in `contact.py:` `z0 = z0.transpose(1, 2)` cannot be operated on a 2d tensor. 

Is it possible to be a bug, or am I misunderstanding something? Thank you!

**Comment by samsledje** [comment]
Hi Xingyu,

Thanks for the comment. The embeddings as created by the `dscript embed` command already have the batch dimension, so when they are loaded from the dictionary in lines 250,251, they are (1, N, d) already, and passed into `model.map_predict` as such.
