### ISSUE TITLE
The API docs is incomplete for prediction

### ISSUE THREAD

**Issue by Moeinh77** [samsledje/D-SCRIPT#48]
Hi I have been trying to use the API but I haven't figured it out, seems like the documentation for the prediction is in complete. If I want to do the equivalent of ```dscript predict [-h] --pairs PAIRS --model MODEL [--seqs SEQS] [--embeddings EMBEDDINGS] [-o OUTFILE] [-d DEVICE] [--thresh THRESH]``` with the API, what should I write? I found this ```dscript.commands.predict.PredictionArguments(cmd, device, embeddings, outfile, seqs, model, thresh, func)``` but I am unsure what is cmd and func. Would you mind showing me an example. Thank you.

**Comment by samsledje** [comment]
Hi Moein, thanks for the comment! The file you're looking at is for the command line interface, which I wouldn't recommend to use as an API. Instead, I would recommend using dscript.language_model and dscript.pretrained to load the embeddings for your sequences, load a pretrained model, and call the model forward method with the embeddings to make predictions. Sequence reading is best done with an external library like BioPython SeqIO.
