### ISSUE TITLE
extract-3di command fail

### ISSUE THREAD

**Issue by twaksman001** [samsledje/D-SCRIPT#54]
[extract-3di_textprinted.txt](https://github.com/samsledje/D-SCRIPT/files/12311823/extract-3di_textprinted.txt)

**Comment by samsledje** [comment]
Can you please run the following commands and let me know at what point it fails and what output you get?

`mkdir /tmp/foldseek_tmpdir`
`foldseek createdb ../data/Mp PDB/Mp41_AF2.pdb ../data/Mp PDB/Mp23_AF2.pdb /tmp/foldseek_tmpdir/test_run`
`ls /tmp/foldseek_tmpdir`
`head /tmp/foldseek_tmpdir/test_run_ss`

**Comment by twaksman001** [comment]
any idea what the problem is?

could it be due to "_ss" not being part of the temporary directory name?

**Comment by samsledje** [comment]
Sorry for the late reply! The `_ss` is the file containing the 3Di sequences, which should be generated by FoldSeek in the temporary directory. It seems that foldseek is running properly given the test commands you sent above -- which means I'm unsure why your original run failed. Could you re-run the original command giving you the issues, and share with me the contents of the temporary directory? This file path is the last part of the foldseek command which is printed ("/tmp/1300970.1.all.q/tmp3aozx6xb/1446002179529316489" in your original error log)

**Comment by twaksman001** [comment]
now, the same problem is occurring, and it appears that the /tmp directory does not contain a directory called "[_job ID_].1.all.q". I seem to remember that this was not the case when I tried a couple of weeks ago, I think I found the temporary directory in the /tmp directory. Also, trying the foldseek command you suggested in your previous [comment](https://github.com/samsledje/D-SCRIPT/issues/54#issuecomment-1675161133) returned error this time: Could not open /tmp/foldseek_tmpdir/test_run_ss.0 for writing!

**Comment by samsledje** [comment]
Can you provide more details about your operating system/environment? We use the Python `tempfile` API to create and write to temporary directories -- if you're unable to create these temporary directories, there might be some permissions error.

**Comment by twaksman001** [comment]
- operating system: linux
- it is a high performance computing resource (HPC) managed by my university
- I don't think I can find much more details without asking specific questions to the managers
- I see that the /tmp folder, which seems to permanently exist on the HPC and is full of various folders and files, has different permissions to all other folders - "drwxrwxrwt."
- conda environment .yml attached
/ (I don't think this causes problems, because I have been able to run Topsy-Turvy non-3D on thousands of proteins)
[bio1_UoD.txt](https://github.com/samsledje/D-SCRIPT/files/12535631/bio1_UoD.txt)

**Comment by twaksman001** [comment]
information from the HPC managers:

- the t flag in /tmp permissions is normal
- /tmp/$JOBID.all.q will exist only on the exec host that ran the job and the scheduler will automatically destroy it once the job completes
- maybe try to use a tmpdir in your datadir on /cluster

Could I make some change to the D-SCRIPT .py files to make the Python tempfile package write to my own directory?

**Comment by twaksman001** [comment]
Everything worked using a different HPC.

**Comment by samsledje** [comment]
Great, let me know if you have any other questions!
