### ISSUE TITLE
How to train D-SCRIPT end-to-end?

### ISSUE THREAD

**Issue by DragonDescentZerotsu** [samsledje/D-SCRIPT#58]
I find in the dscript/commands/train.py that the training takes the embedded features and only trains the projection and CNN module. 
How can I train the language, the BiLSTM, together with the projection and CNN module?

**Comment by samsledje** [comment]
Hi @DragonDescentZerotsu ,

The package was designed to train just the D-SCRIPT model, and take language model embeddings as an input. To train an entire model end-to-end, including the parameters of the language model, I would recommend forking the repository and editing the code yourself so your language model of choice is part of the model which is optimized during the training loop. We don't currently have plans to support full end-to-end training including the language model in this package.
