### ISSUE TITLE
proteinA x proteinB skipped (The size of tensor a (2581) must match the size of tensor b (2000)

### ISSUE THREAD

**Issue by zhijs** [samsledje/D-SCRIPT#61]
hi~, I try to use this great tool to prodict specific sequence protein interactions, and I got the above messages in the log file, what these messages mean or does it affect predicted interaction value?
I use conda to install and predicted use trained model, the predicted command showed below.
`dscript predict --pairs ./pair.tsv --seqs ./sequence.fasta --model  ./topsy_turvy_v1.sav`

**Comment by samsledje** [comment]
We don't recommend that you use D-SCRIPT on protein sequences longer than ~1500 amino acids long, both for accuracy and compute efficiency reasons. If you'd still like to make predictions with these proteins, we would recommend cropping to ~800aa size chunks, treating each as a separate "protein" at inference time, and then taking the maximum p(Interaction) over the different crops.
