### ISSUE TITLE
Queries about  sequence identity in the dataset

### ISSUE THREAD

**Issue by sirius777coder** [samsledje/D-SCRIPT#65]
Hi, I really like your work and idea. I have a question about the sequence identity in your paper:

> "Next, we removed PPIs with high sequence redundancy to other PPIs, following the precedent of previous approaches. Specifically, we clustered proteins at the 40% similarity threshold using CD-HIT, and a PPI (A-B) was considered sequence redundant (and excluded) if we had already selected another PPI (C-D) such that the protein pairs (A, C) and (B, D) each shared a CD-HIT cluster"

When considering three proteins A, B, and C with interactions between A-B and A-C, how do you address this redundancy? Do you assess the redundancy for pair A-A, B-C or focus on A-C and B-A instead? I think it is totally different.

**Comment by samsledje** [comment]
Hi @sirius777coder , in this case, A-B, A-C will be considered redundant if B and C are in the same CD-HIT cluster.

**Comment by sirius777coder** [comment]
Great! Does your code contain any processing codes related to the dataset?

**Comment by AccMLBioWorkshop** [comment]
No, this code is meant for the package itself.

**Comment by samsledje** [comment]
No, this repository is meant to contain just the package itself, for general model training and inferences.
