### ISSUE TITLE
The size of tensor a (4268) must match the size of tensor b (2000) at non-singleton dimension 2

### ISSUE THREAD

**Issue by Lsz-20** [samsledje/D-SCRIPT#68]
Hello, I'm trying to run my dataset with dscript train
But it shows me this ：
RuntimeError: The size of tensor a (4268) must match the size of tensor b (2000) at non-singleton dimension 2
How can i solve this problem?

**Comment by samsledje** [comment]
Hi @Lsz-20 , D-SCRIPT does not support proteins longer than 2000 amino acids. I would recommend cropping your protein and potentially making multiple predictions on different crops ~1200 AA long, then taking the maximum value.
