### ISSUE TITLE
maybe a typo bug

### ISSUE THREAD

**Issue by jiyanbio** [samsledje/D-SCRIPT#7]
In contact.py,
   def forward(self, z0, z1):
        """
        :param z0: Projection module embedding :math:`(b \\times N \\times d)`
        :type z0: torch.Tensor
        :param z1: Projection module embedding :math:`(b \\times M \\times d)`
        :type z1: torch.Tensor
        :return: Predicted contact map :math:`(b \\times N \\times M)`
        :rtype: torch.Tensor
        """
        B = self.broadcast(z0, z1)
        return self.predict(**C**)

should it be **B**?

**Comment by samsledje** [comment]
Thanks @jiyanbio! Fixed in [0.1.4](https://pypi.org/project/dscript/0.1.4/). Can I ask what use case led you to finding this bug?

**Comment by jiyanbio** [comment]
> Thanks @jiyanbio! Fixed in [0.1.4](https://pypi.org/project/dscript/0.1.4/). Can I ask what use case led you to finding this bug?

when reading your codes, I found it by chance.
